version: '3.9'

services:

  ##Eureka Server
  discovery-server:
    image: wasim02/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin

  api-gateway:
    image: wasim02/api-getway:latest
    container_name: api-gateway
    network_mode: host
    depends_on:
      - zipkin
      - discovery-server
      - auth-server


  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  auth-server:
    container_name: auth-server
    image: wasim02/auth-server:latest
    network_mode: host
    depends_on:
      - discovery-server

  #product-service
  product-service:
    container_name: product-service
    image: product-service:latest
    network_mode: host
    depends_on:
      - discovery-server
      - api-gateway

  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product-service

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    user: root:root
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
